title: Oinam Jekyll
description: A simple, clean, and minimal Jekyll Theme.
url: ''
baseurl: ''

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

plugins:
 - jekyll-optional-front-matter
 - jekyll-titles-from-headings

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

sass:
  style: compressed
  sourcemap: never

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - gemfiles/
  - Gemfile.lock
  - LICENSE.*
  - netlify.toml
  - node_modules/
  - README.*
  - vendor/
