title: Oinam Jekyll
description: Clean, Simple, and Minimal Design.

# Set this to your domain; baseurl is for the folder in your domain, if you have one -- `blog`.
# you can leave both of them blank if you are deploying on a top-level domain.
url: https://oinam.github.io
baseurl: /oinam-jekyll

# footer
footer:
  credit: true
  custom: false

# if above footer:custom is 'true', then this will be printed instead
footer_custom: 'An ever Work-in-Progress effort by <a href="https://oinam.com">Oinam</a>.'

# Styles
styles:
  font_family: sans # serif, sans

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

plugins:
 - jekyll-optional-front-matter
 - jekyll-titles-from-headings

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

sass:
  style: compressed
  sourcemap: never

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - netlify.toml
  - node_modules/
  - oinam-jekyll.gemspec
  - README.*
  - server
  - vendor/