title: Oinam Jekyll
description: A simple, clean, and minimal Jekyll Theme.

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

feed:
  posts_limit: 10
  author: Brajeshwar

kramdown:
  input: GFM
  syntax_highlighter: rouge
  default_lang: html
  css_class: syntax

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

sass:
  style: compressed
  sourcemap: never

plugins:
 - jekyll-feed

exclude:
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.*
  - oinam-*.gem
  - oinam.gemspec
  - README.*
