title: Oinam Jekyll
description: A simple, clean, and minimal Jekyll Theme.

remote_theme: oinam-jekyll
markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

sass:
  style: compressed
  sourcemap: never

plugins:
 - jekyll-feed

exclude:
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.*
  - oinam-*.gem
  - oinam.gemspec
  - README.*
  - oinam-jekyll-cover.png
