title: Oinam Jekyll
description: A simple, clean, and minimal Jekyll Theme.

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

sass:
  style: compressed
  sourcemap: never

theme: oinam

plugins:
 - jekyll-feed
