title: Oinam Jekyll
description: A simple, clean, and minimal Jekyll Theme.

theme: null
markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

sass:
  style: compressed
  sourcemap: never

plugins:
 - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.*
  - README.*
  - netlify.toml
